blank_issues_enabled: false
contact_links:
  - name: 💬 Discussion Forum
    url: https://github.com/open-syntax/ultimatexo/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Documentation
    url: https://github.com/open-syntax/ultimatexo#readme
    about: Read the documentation
  - name: 🔒 Security Issue
    url: https://github.com/open-syntax/ultimatexo/security/advisories/new
    about: Report a security vulnerability privately
